# Generated by Django 5.2 on 2025-04-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_tip',
            field=models.TextField(blank=True, help_text='Stores the daily financial tip.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_tip_date',
            field=models.DateField(blank=True, help_text='The date the last daily tip was generated.', null=True),
        ),
    ]
