# Generated by Django 5.2 on 2025-04-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_daily_tip_user_last_tip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plaid_access_token',
            field=models.CharField(blank=True, help_text='Plaid access token for the user', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plaid_institution_name',
            field=models.CharField(blank=True, help_text='Name of the institution linked via Plaid', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plaid_item_id',
            field=models.CharField(blank=True, help_text='Plaid item ID for the user', max_length=255, null=True),
        ),
    ]
