# Generated by Django 5.2 on 2025-04-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_plaid_access_token_user_plaid_institution_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plaid_sync_cursor',
            field=models.CharField(blank=True, help_text='Cursor for the next Plaid transaction sync', max_length=255, null=True),
        ),
    ]
