# Generated by Django 4.2.20 on 2025-04-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("food", "Food"),
                    ("entertainment", "Entertainment"),
                    ("shopping", "Shopping"),
                    ("transportation", "Transportation"),
                    ("subscriptions", "Subscriptions"),
                ],
                max_length=100,
            ),
        ),
    ]
