# Generated by Django 5.2 on 2025-04-23 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pending',
            field=models.BooleanField(default=False, help_text='Whether the transaction is still pending'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='plaid_account_id',
            field=models.CharField(blank=True, help_text='Account ID from Plaid', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='plaid_transaction_id',
            field=models.CharField(blank=True, help_text='Unique ID from Plaid for this transaction', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('transportation', 'Transportation'), ('subscriptions', 'Subscriptions'), ('housing', 'Housing'), ('utilities', 'Utilities'), ('healthcare', 'Healthcare'), ('income', 'Income'), ('personal_care', 'Personal Care'), ('travel', 'Travel'), ('education', 'Education'), ('gifts_donations', 'Gifts/Donations'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('user', 'plaid_transaction_id'), name='unique_user_plaid_transaction'),
        ),
    ]
