# Generated by Django 5.2 on 2025-04-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcategory',
            name='name',
            field=models.CharField(choices=[('food', 'Food'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('transportation', 'Transportation'), ('subscriptions', 'Subscriptions')], max_length=100),
        ),
    ]
