# Generated by Django 5.2 on 2025-04-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_monthlybudget_ai_suggestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcategory',
            name='name',
            field=models.CharField(choices=[('food', 'Food'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('transportation', 'Transportation'), ('subscriptions', 'Subscriptions'), ('housing', 'Housing'), ('utilities', 'Utilities'), ('healthcare', 'Healthcare'), ('income', 'Income'), ('personal_care', 'Personal Care'), ('travel', 'Travel'), ('education', 'Education'), ('gifts_donations', 'Gifts/Donations'), ('other', 'Other')], max_length=100),
        ),
    ]
