# Generated by Django 5.2 on 2025-04-23 18:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_budgetcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybudget',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Automatically updated spent amount for this budget month.', max_digits=10),
        ),
    ]
